### PR TITLE
feat: Word Count Log File GitHub Action

### LINKED ISSUE #21: Word Count Log File GitHub Action
[Issuehunt badges](https://issuehunt.io/r/singularityhacker/Content/issues/21)

**As a:** writer using GitHub as my writing platform.

**I want to:** know how many new words are included in commits.

**So that:** I can set goals for myself about writing a minimum number of words a day.

Notes:

I'm thinking the way this could work is 

1.  Install ubuntu
2.  Install Node (I'm more comfortable making changes to a node script in the future)
3.  Subtract the difference in word count on changed files (node package [candidate](https://www.npmjs.com/package/word-counting))
4.  Append this word count to the bottom of a log file in the repo. Ex:
    1.  +100 words to \[file name\]
    2.  \-30 words to \[file name\]
5.  Don't rerun the action when the logfile gets update otherwise it would create an infinite loop.

But I leave implementation details to your best judgment.

See my recent feeble attempt to get this going: https://github.com/singularityhacker/Content/blob/master/.github/workflows/actions.yml

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [singularityhacker singularityhacker](https://issuehunt.io/u/singularityhacker) ($60.00)

### Submitted pull Requests
- [#22 feat: Word Count Log File GitHub Action](https://issuehunt.io/r/singularityhacker/Content/pull/22)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/singularityhacker/Content/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by mcmxcdev**
Phew, this was quite a lot of work, but fun!

I hope the implementation is how you would imagine it ;)

The `logfile.json` displays all blog posts with initial words
As soon as there is a diff because of rewriting files, you can see a ISO timestamp with the diff to the previous number of words and now current words.

To try it out locally: 
- clear content of `logfile.json`, just leave it an empty object
- run `node wordCount.js`
- expect initial filling of all markdown files into `logfile.json` 
-  add or delete some markdown file content
- run `node wordCount.js`
- expect timestamp with diff and new word count in object key with name of blog post

I will implement the GitHub action when you say this is how you want it! Should just be a matter of running `node wordCount.js` on `git push`.

Closes #21.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#21: Word Count Log File GitHub Action](https://issuehunt.io/repos/272111351/issues/21)
---
</details>

### CODE REVIEW

**Comment by singularityhacker** [comment]
You are the man! I'm not able to run locally for some reason. Getting the following error:

BKSQ-XL0J-MAC:content conderj$ node wordCount.js

/Users/conderj/content/wordCount.js:48

      const wordCountExisting = currentWords ?? existingFileName.initialWords;

SyntaxError: Unexpected token '?'

    at wrapSafe (internal/modules/cjs/loader.js:1053:16)

    at Module.\_compile (internal/modules/cjs/loader.js:1101:27)

    at Object.Module.\_extensions..js (internal/modules/cjs/loader.js:1157:10)

    at Module.load (internal/modules/cjs/loader.js:985:32)

    at Function.Module.\_load (internal/modules/cjs/loader.js:878:14)

    at Function.executeUserEntryPoint \[as runMain\] (internal/modules/run\_main.js:71:12)

    at internal/main/run\_main\_module.js:17:47

**Comment by singularityhacker** [comment]
I can still merge the pull request if it helps you debug/move forward. As long as it works in the action, I can always figure out what's wrong on local later.

**Comment by mcmxcdev** [comment]
Sorry, my bad.
The issue is that you probably are not using node 14, am I right?

The `??` operator is quite new, replace it on your machine with `||` for now and you will be able to run it. There is an edge case for markdown files without any words where it doesn't work, so I will find a fix in the meantime!

No need for merging yet, I will work on the action file next.

**Comment by mcmxcdev** [comment]
I have good news! 

I updated the GitHub action file and it works perfectly: 
- it now uses Node v10 (oldest version that is still supported)
- installs dependencies
- runs `node wordCount.js` and then
- adds, commit and pushes the changes to the `logfile.json`

You can go through the commit history of this PR to see what exactly is happening.

If you ever need GitHub actions more often, you can use this helpful library to run them locally: https://github.com/nektos/act

Currently, the GitHub action is triggered on a push in any branch. I can specify this to be master only.
It depends on how often you want to see the changes, and if you work with branches a lot or mainly push to master.

When you decide this is the way you want it, I would:
- remove `testfile.md`
- change back `logfile.json` to be empty object, so that it gets initialized on push
- (optional) change actions to trigger for master only
- squash merge into master when it is ready to avoid unnecessary commits that were necessary to test

And BIG thanks for your GitHub Sponsors support!! :tada: 
Just hit me up whenever you need some work done.

**Comment by singularityhacker** [comment]
THIS is a thing of beauty! I love the way you record the log as a json file too. Opens the door to build a dashboard using Netlify. Thank you so much for the time you spent on this. We have a lot of similar interests (jamstack, svelte, IF, EDM, crypto, etc) so I'm honored to be your first sponsor.

**Comment by mcmxcdev** [comment]
I am glad you like it!
Yeah, using a JSON file instead of a simple text file enables you to do a lot of stuff with the data and you have a super nice diff log that is displaying step by step. I also made sure all the variable names make sense, so you can do easy changes.

Haha, cool that you are also interested in all of these things :smile:

**Pull request merged**
